Update vuex-store.md
quasarframework/quasar pull request #10919
Opened 2021-10-07 14:26 UTC by kostyfisik

I am new to quasar\vue\vuex\typescript. So getting these two lines of code took me quite a while, the most helpfull was https://forum.quasar-framework.org/topic/7887/best-way-for-implement-vuex-with-typescript/5  (however, it also was far from being obvious that from the whole post I just neet two lines, modified with correct names)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [X] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2021-10-07 17:38 UTC, hawkeye64 commented on docs/src/pages/quasar-cli/vuex-store.md
> +To get a typed vuex store in your component you will need to modify you vue file like this:
Grammer fix needed
"...modify **your** Vue..."

2021-10-08 08:01 UTC, yusufkandemir requested changes
Thanks for documenting these changes 👍 I made some recommendations, please make those changes.

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +If you choose to use Vuex and TypeScirpt when you create a project folder with Quasar CLI, it will add some typing code in `src/store/index.ts`.
```suggestion
If you choose to use Vuex and TypeScript when you create a project folder with Quasar CLI, it will add some typing code in `src/store/index.ts`.
```

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +To get a typed vuex store in your component you will need to modify you vue file like this:
```suggestion
To get a typed Vuex store in your component you will need to modify your Vue file like this:
```

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +}
There is also `useStore` helper in the `src/store` file, which is easier/shorter to use.
```suggestion
import { defineComponent } from 'vue';
import { useStore } from 'src/store';

export default defineComponent({
  setup () {
    const $store = useStore()
    // You can use the $store, example: $store.state.someStoreModule.someData
  }
})
```

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +
There are excessive empty lines, please remove them.
```suggestion
```

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +## TypeScript support
Please add an empty line before this section to improve code readability.
```suggestion

## TypeScript support
```

2021-10-08 08:01 UTC, yusufkandemir commented on docs/src/pages/quasar-cli/vuex-store.md
> +<!--    Your code-->
```suggestion
  <!-- ... -->
```

2021-10-08 10:45 UTC, merged

2021-10-08 10:46 UTC, kostyfisik commented
@yusufkandemir @hawkeye64 Thank you for you help! Sorry for so many typos, I've decided that it is better to provide some input and iteratively impove it instead of not providing a polished one. GitHub interface commits for every resolved edit, but it is easy to squash\rebase during merge to remove burden from project`s git log.

2021-10-08 13:06 UTC, hawkeye64 commented
Thanks for contributing!