feat(ts&api): Generate inline function types, improve some types
quasarframework/quasar pull request #11109
Opened 2021-10-26 09:16 UTC by yusufkandemir

**What kind of change does this PR introduce?**

- Feature
- Code style update
- Refactor

**Does this PR introduce a breaking change?**

- No

**The PR fulfills these requirements:**

- It's submitted to the `dev` branch

**Other information:**
Please see commit messages and descriptions for more info.

Notable changes:
 - Updated JSON API definitions of lots of `Function` typed properties
 - We are now generating TS definitions for function typed function parameters(_e.g. callbacks_) and functions in union types(_e.g. props which accepts a value or a function that returns that value_).
 - Return types of some methods had all properties as optional, but they should have been required, they are fixed:
   - `QScrollArea.getScroll`
   - `QScrollArea.getScrollPosition`
   - `QScrollArea.getScrollPercentage`
 - The parameter of `DialogChainObject.update` was optional before, which was wrong, it's now required.

`dist/types/index.d.ts` diff: 
```diff
@@ -408,7 +408,7 @@ export interface LocalStorage {
       | RegExp
       | number
       | boolean
-      | Function
+      | ((...params: any[]) => any)
       | LooseDictionary
       | any[]
       | string
@@ -549,7 +549,7 @@ export interface Notify {
           /**
            * Function to call when notification gets dismissed
            */
-          onDismiss?: Function;
+          onDismiss?: () => void;
           /**
            * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
            */
@@ -564,7 +564,85 @@ export interface Notify {
           ignoreDefaults?: boolean;
         }
       | string
-  ) => Function;
+  ) => (props: {
+    /**
+     * Optional type (that has been previously registered) or one of the out of the box ones ('positive', 'negative', 'warning', 'info', 'ongoing')
+     */
+    type: string;
+    /**
+     * Color name for component from the Quasar Color Palette
+     */
+    color: string;
+    /**
+     * Color name for component from the Quasar Color Palette
+     */
+    textColor: string;
+    /**
+     * The content of your message
+     */
+    message: string;
+    /**
+     * The content of your optional caption
+     */
+    caption: string;
+    /**
+     * Render message as HTML; This can lead to XSS attacks, so make sure that you sanitize the message first
+     */
+    html: boolean;
+    /**
+     * Icon name following Quasar convention; Make sure you have the icon library installed unless you are using 'img:' prefix
+     */
+    icon: string;
+    /**
+     * URL to an avatar/image; Suggestion: use statics folder
+     */
+    avatar: string;
+    /**
+     * Useful for notifications that are updated; Displays a Quasar spinner instead of an avatar or icon; If value is Boolean 'true' then the default QSpinner is shown
+     */
+    spinner: boolean | Component;
+    /**
+     * Show progress bar to detail when notification will disappear automatically (unless timeout is 0)
+     */
+    progress: boolean;
+    /**
+     * Class definitions to be attributed to the progress bar
+     */
+    progressClass: any[] | string | LooseDictionary;
+    /**
+     * Add CSS class(es) to the notification for easier customization
+     */
+    classes: string;
+    /**
+     * Key-value for attributes to be set on the notification
+     */
+    attrs: LooseDictionary;
+    /**
+     * Amount of time to display (in milliseconds)
+     * Default value: 5000
+     */
+    timeout: number;
+    /**
+     * Notification actions (buttons); If a 'handler' is specified or not, clicking/tapping on the button will also close the notification; Also check 'closeBtn' convenience prop
+     */
+    actions: any[];
+    /**
+     * Function to call when notification gets dismissed
+     */
+    onDismiss: () => void;
+    /**
+     * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
+     */
+    closeBtn: boolean | string;
+    /**
+     * Put notification into multi-line mode; If this prop isn't used and more than one 'action' is specified then notification goes into multi-line mode by default
+     */
+    multiLine: boolean;
+    /**
+     * Ignore the default configuration (set by setDefaults()) for this instance only
+     */
+    ignoreDefaults: boolean;
+  }) => void;
   /**
    * Merge options into the default ones
    * @param opts Notification options
@@ -669,7 +747,7 @@ export interface Notify {
     /**
      * Function to call when notification gets dismissed
      */
-    onDismiss?: Function;
+    onDismiss?: () => void;
     /**
      * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
      */
@@ -786,7 +864,7 @@ export interface Notify {
       /**
        * Function to call when notification gets dismissed
        */
-      onDismiss?: Function;
+      onDismiss?: () => void;
       /**
        * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
        */
@@ -1015,7 +1093,7 @@ export interface SessionStorage {
       | RegExp
       | number
       | boolean
-      | Function
+      | ((...params: any[]) => any)
       | LooseDictionary
       | any[]
       | string
@@ -1974,7 +2052,7 @@ export interface QBtnProps {
    * @param evt JS event object; If you want to cancel navigation set synchronously 'evt.navigate' to false
    * @param navigateFn When you need to control the time at which the button should trigger the route navigation then set 'evt.navigate' to false and call this function; Useful if you have async work to be done before the actual route navigation
    */
-  onClick?: (evt: LooseDictionary, navigateFn: Function) => void;
+  onClick?: (evt: LooseDictionary, navigateFn: () => void) => void;
 }
 
 export interface QBtnSlots {
@@ -2267,7 +2345,7 @@ export interface QCarouselSlots {
     /**
      * Default trigger when clicked/tapped on
      */
-    onClick: Function;
+    onClick: (evt: LooseDictionary) => void;
   }) => VNode[];
 }
 
@@ -2893,15 +2971,15 @@ export interface QDateProps {
   /**
    * A list of events to highlight on the calendar; If using a function, it receives the date as a String and must return a Boolean (matches or not); If using a function then for best performance, reference it from your scope and do not define it inline
    */
-  events?: any[] | Function | undefined;
+  events?: any[] | ((date: string) => boolean) | undefined;
   /**
    * Color name (from the Quasar Color Palette); If using a function, it receives the date as a String and must return a String (color for the received date); If using a function then for best performance, reference it from your scope and do not define it inline
    */
-  eventColor?: string | Function | undefined;
+  eventColor?: string | ((date: string) => string) | undefined;
   /**
    * Optionally configure the days that are selectable; If using a function, it receives the date as a String and must return a Boolean (is date acceptable or not); If using a function then for best performance, reference it from your scope and do not define it inline; Incompatible with 'range' prop
    */
-  options?: any[] | Function | undefined;
+  options?: any[] | ((date: string) => boolean) | undefined;
   /**
    * Lock user from navigating below a specific year+month (in YYYY/MM format); This prop is not used to correct the model; You might want to also use 'default-year-month' prop
    */
@@ -3523,7 +3601,7 @@ export interface QEditorProps {
         /**
          * Either this or "cmd" is required. Function for when button gets clicked/tapped.
          */
-        handler?: Function;
+        handler?: () => void;
   [...]

2021-10-26 09:48 UTC, rstoenescu commented
Haven't tested, but looks awesome! Cool work @yusufkandemir !
Ping me when u think it's ready (saw the "draft" badge).

2021-10-26 14:40 UTC, IlCallo commented on ui/build/build.types.js
> -  const t = type.trim()
Any ideas why this was needed in the first place?

2021-10-26 14:40 UTC, IlCallo commented on ui/build/build.types.js
> +// TODO: Consider removing the indenting logic as it's already handled better and gets overridden by prettier
I agree we can get rid of this, since we format everything with Prettier after generation

2021-10-26 14:44 UTC, yusufkandemir commented on ui/build/build.types.js
> -  const t = type.trim()
I explained it on the related commit's message. There were some types that had trailing spaces for some reason, I updated them as well. I don't know why there were trailing spaces on some types though.

2021-11-03 07:51 UTC, rstoenescu commented
Hi @yusufkandemir 

What's the status on this one? I'd like to push it and release the next Quasar version.

2021-11-03 09:47 UTC, yusufkandemir commented
The return type of `Notify.create` was `Function` which was not correct, it's now better but all properties are required. I left a FIXME note about it. I have a fix for that along with a lot of other stuff, but it requires a "revamp" for `tsType`, and it's still WIP. It would probably be a better idea to do it in another PR, so I think this PR is ready to be reviewed and then merged.

`dist/types/index.d.ts` diff after the last changes:
```diff
@@ -408,7 +408,7 @@ export interface LocalStorage {
       | RegExp
       | number
       | boolean
-      | Function
+      | ((...params: any[]) => any)
       | LooseDictionary
       | any[]
       | string
@@ -549,7 +549,7 @@ export interface Notify {
           /**
            * Function to call when notification gets dismissed
            */
-          onDismiss?: Function;
+          onDismiss?: () => void;
           /**
            * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
            */
@@ -564,7 +564,85 @@ export interface Notify {
           ignoreDefaults?: boolean;
         }
       | string
-  ) => Function;
+  ) => (props: {
+    /**
+     * Optional type (that has been previously registered) or one of the out of the box ones ('positive', 'negative', 'warning', 'info', 'ongoing')
+     */
+    type: string;
+    /**
+     * Color name for component from the Quasar Color Palette
+     */
+    color: string;
+    /**
+     * Color name for component from the Quasar Color Palette
+     */
+    textColor: string;
+    /**
+     * The content of your message
+     */
+    message: string;
+    /**
+     * The content of your optional caption
+     */
+    caption: string;
+    /**
+     * Render message as HTML; This can lead to XSS attacks, so make sure that you sanitize the message first
+     */
+    html: boolean;
+    /**
+     * Icon name following Quasar convention; Make sure you have the icon library installed unless you are using 'img:' prefix
+     */
+    icon: string;
+    /**
+     * URL to an avatar/image; Suggestion: use statics folder
+     */
+    avatar: string;
+    /**
+     * Useful for notifications that are updated; Displays a Quasar spinner instead of an avatar or icon; If value is Boolean 'true' then the default QSpinner is shown
+     */
+    spinner: boolean | Component;
+    /**
+     * Show progress bar to detail when notification will disappear automatically (unless timeout is 0)
+     */
+    progress: boolean;
+    /**
+     * Class definitions to be attributed to the progress bar
+     */
+    progressClass: any[] | string | LooseDictionary;
+    /**
+     * Add CSS class(es) to the notification for easier customization
+     */
+    classes: string;
+    /**
+     * Key-value for attributes to be set on the notification
+     */
+    attrs: LooseDictionary;
+    /**
+     * Amount of time to display (in milliseconds)
+     * Default value: 5000
+     */
+    timeout: number;
+    /**
+     * Notification actions (buttons); If a 'handler' is specified or not, clicking/tapping on the button will also close the notification; Also check 'closeBtn' convenience prop
+     */
+    actions: any[];
+    /**
+     * Function to call when notification gets dismissed
+     */
+    onDismiss: () => void;
+    /**
+     * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
+     */
+    closeBtn: boolean | string;
+    /**
+     * Put notification into multi-line mode; If this prop isn't used and more than one 'action' is specified then notification goes into multi-line mode by default
+     */
+    multiLine: boolean;
+    /**
+     * Ignore the default configuration (set by setDefaults()) for this instance only
+     */
+    ignoreDefaults: boolean;
+  }) => void;
   /**
    * Merge options into the default ones
    * @param opts Notification options
@@ -669,7 +747,7 @@ export interface Notify {
     /**
      * Function to call when notification gets dismissed
      */
-    onDismiss?: Function;
+    onDismiss?: () => void;
     /**
      * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
      */
@@ -786,7 +864,7 @@ export interface Notify {
       /**
        * Function to call when notification gets dismissed
        */
-      onDismiss?: Function;
+      onDismiss?: () => void;
       /**
        * Convenience way to add a dismiss button with a specific label, without using the 'actions' prop; If set to true, it uses a label accordding to the current Quasar language
        */
@@ -1015,7 +1093,7 @@ export interface SessionStorage {
       | RegExp
       | number
       | boolean
-      | Function
+      | ((...params: any[]) => any)
       | LooseDictionary
       | any[]
       | string
@@ -1974,7 +2052,7 @@ export interface QBtnProps {
    * @param evt JS event object; If you want to cancel navigation set synchronously 'evt.navigate' to false
    * @param navigateFn When you need to control the time at which the button should trigger the route navigation then set 'evt.navigate' to false and call this function; Useful if you have async work to be done before the actual route navigation
    */
-  onClick?: (evt: LooseDictionary, navigateFn: Function) => void;
+  onClick?: (evt: LooseDictionary, navigateFn: () => void) => void;
 }
 
 export interface QBtnSlots {
@@ -2267,7 +2345,7 @@ export interface QCarouselSlots {
     /**
      * Default trigger when clicked/tapped on
      */
-    onClick: Function;
+    onClick: (evt: LooseDictionary) => void;
   }) => VNode[];
 }
 
@@ -2893,15 +2971,15 @@ export interface QDateProps {
   /**
    * A list of events to highlight on the calendar; If using a function, it receives the date as a String and must return a Boolean (matches or not); If using a function then for best performance, reference it from your scope and do not define it inline
    */
-  events?: any[] | Function | undefined;
+  events?: any[] | ((date: string) => boolean) | undefined;
   /**
    * Color name (from the Quasar Color Palette); If using a function, it receives the date as a String and must return a String (color for the received date); If using a function then for best performance, reference it from your scope and do not define it inline
    */
-  eventColor?: string | Function | undefined;
+  eventColor?: string | ((date: string) => string) | undefined;
   /**
    * Optionally configure the days that are selectable; If using a function, it receives the date as a String and must return a Boolean (is date acceptable or not); If using a function then for best performance, reference it from your scope and do not define it inline; Incompatible with 'range' prop
    */
-  options?: any[] | Function | undefined;
+  options?: any[] | ((date: string) => boolean) | undefined;
   /**
    * Lock user from navigating below a specific year+month (in YYYY/MM format); This prop is not used to correct the model; You might want to also use 'default-year-month' prop
    */
@@ -3523,7 +3601,7 @@ export interface QEditorProps {
         /**
          * Either this or "cmd" is required. Function for when button gets clicked/tapped.
          */
-        handler?: Function;
+        handler?: () => void;
         /**
          * Either this or "handler" is required. This must be a valid execCommand method according to the designMode API.
          */
@@ -3533,9 +3611,9 @@ export interface QEditorProps {
          */
         param?: string;
         /**
-         * Is button disabled? If specifying a function, return a Boolean value.
+         * Is button disabled?
          */
-        disable?: boolean | Function;
+        disable?: boolean | (() => boolean);
         /**
          * Pass the value "no-sta [...]

2021-11-03 10:27 UTC, IlCallo commented
Seems like you also removed optionality from some `QScrollArea` properties, is that correct or due to the same problem as `Notify.create`?

@rstoenescu since it introduces some type changes which may case confusion into users, I think it's better if this goes into a future release together with those problems fix, not the next release

2021-11-03 10:37 UTC, IlCallo approved these changes

2021-11-03 17:55 UTC, rstoenescu commented
Sure, will wait until it's 100% ready.
Great work on these improvements!

2021-11-08 15:32 UTC, yusufkandemir commented
I applied a workaround as per @IlCallo's suggestion. I also made some fixes to the `build.api.js` script.
@rstoenescu it's now ready to be reviewed/merged.

There are still other kinds of improvements to be made, which will come in on separate PRs.

2021-11-08 18:33 UTC, IlCallo approved these changes

2021-11-08 18:34 UTC, IlCallo commented
Not sure about the build API part as it isn't super clear what the code is doing in the first place, but the types part seems ok now
If you tested it on that side and saw no side effects, I can merge

2021-11-09 11:42 UTC, yusufkandemir commented
@IlCallo the API build part is basically validating the API schemas by checking if there are any required props(e.g. `desc`, `examples`) missing, or any unrecognized props(e.g. `foo`, `exampels`(_typo_)) are used and then validating the type(boolean/object/array) of the prop. But I noticed that it has some weak/broken spots, and fixed them. So, of course, I tested it to see if it's allowing invalid data in or not while playing around with it. But, I think it may be a good idea if @rstoenescu can review that part specifically.

2021-11-09 14:27 UTC, rstoenescu requested changes

2021-11-09 14:27 UTC, rstoenescu commented on ui/build/build.types.js
> +    // Set paramsRequired to false for the function returned from Notify.create(...)
Let's add a "requiredParams: false" to the API on the same level as "params" in such cases.

2021-11-09 14:27 UTC, rstoenescu commented on ui/build/build.types.js
> +    // Set paramsRequired to false for the function returned from Notify.create(...)
Otherwise looks really really good!

2021-11-09 14:31 UTC, IlCallo commented on ui/build/build.types.js
> +    // Set paramsRequired to false for the function returned from Notify.create(...)
If I got it right, @yusufkandemir will manage this in a followup PR, gonna merge this for now

2021-11-09 14:31 UTC, merged

2021-11-09 14:33 UTC, rstoenescu commented
Or rather than `requiredParams: false` a "required: true" to all params that are required instead. Might be a lot of work but much more logically.

2021-11-09 14:47 UTC, yusufkandemir commented
I actually went over all the possible cases where things can be required or not, and reworked the 'required' logic. (WIP)

 - For component props:
   - Don't touch 'required' of top-level component properties to allow optional/required props
   - If it's a function, make all params required (1-level deep) since function props are working as callbacks
 - For plugins:
   - Make all top-level properties required, then if it's an object, make all of its properties required recursively.
   - If it's a function, don't touch its parameters or return type
 - Methods should always be required
 - For events:
   - Event listeners are always optional
   - Make all params(payload) required since event listeners are callbacks and will receive all parameters
 - For slots:
   - Slots always exist
   - Make all top-level properties required because they will always exist in the scope
 
Then removed all `required`, `paramsRequired`, etc. params, and started handling it according to `definition.required` which may get overridden outside of the handler functions, according to the rules above. There is one source of truth with sensible defaults now. Then of course had to go over a hell lot of API definitions to make the types right. Also, I found out some wrong types while going over them and fixed them too. Hopefully, I'll make a PR for this soon.

2021-11-09 15:21 UTC, rstoenescu commented
Keep it going. Top notch work!

2021-11-10 10:40 UTC, soulsam480 commented
@yusufkandemir Great to see Quasar moving towards a fully typed lib. Thanks for your hard work

2021-11-10 10:42 UTC, rstoenescu commented
This went into Quasar v2.3.1

2021-11-10 11:20 UTC, soulsam480 commented
Already upgraded. Have some question @yusufkandemir 
![image](https://user-images.githubusercontent.com/35460828/141103952-2dc069ed-c61c-4f37-9a69-916c95bb8bb4.png)

>For events:
Event listeners are always optional
Make all params(payload) required since event listeners are callbacks and will receive all parameters

I understand your reason for making all params in listeners required, but in this case what if I don't have a requirement for after function and even though I'm passing an empty arrow function, eslint is mad. Is there any other way for this ?

2021-11-10 11:26 UTC, soulsam480 commented
And another request, can we export standalone types for these callbacks, will be easy to create typed callbacks. e.g.
```ts
export type FilterFunc = (
    inputValue: string,
    doneFn: (
      callbackFn: () => void,
      afterFn: (ref: LooseDictionary) => void
    ) => void,
    abortFn: () => void
  ) => void;

const myFilterFunc: FilterFunc = (val,update, abort) =>{
....
}

```

2021-11-10 11:46 UTC, yusufkandemir commented
@soulsam480 those changes I mentioned are WIP and not included in this PR. And the condition I mentioned regarding events would say `val` and `update` should always exist, but the parameters of `update`, which are `callbackFn` and `afterFn` in this case, may or may not exist, look for JSON API to decide. So, the types would look like this:
```diff
@@ -8157,9 +8097,9 @@
    * @param doneFn Adds (optional) value to the model; Do not forget to call it after you validate the newly created value; Call it with no parameters if nothing should be added
    */
   onNewValue?: (
     inputValue: string,
-    doneFn: (item: any, mode: "add" | "add-unique" | "toggle") => void
+    doneFn: (item?: any, mode?: "add" | "add-unique" | "toggle") => void
   ) => void;
   /**
    * Emitted when user wants to filter a value
    * @param inputValue What the user typed
@@ -8169,9 +8109,9 @@
   onFilter?: (
     inputValue: string,
     doneFn: (
       callbackFn: () => void,
-      afterFn: (ref: LooseDictionary) => void
+      afterFn?: (ref: Component) => void
     ) => void,
     abortFn: () => void
   ) => void;
```
which is correct if I am not missing something. With the current way the type generation system handles `required` stuff, they are automatically made required, so that's where those new assumptions/rules will come into play, making it a more flexible system. These changes will probably and hopefully come next week because I don't have unlimited time 😄.

For your second request, yes, we are planning to extract some types, especially the ones that are referenced from the outside most like QTable's `onRequest` and `columns` definition, QSelect's `onFilter`, etc.

Thanks for the feedback, it's really valuable ✌️

2021-11-10 12:09 UTC, soulsam480 commented
@yusufkandemir 
> And the condition I mentioned regarding events would say val and update should always exist, but the parameters of update, which are callbackFn and afterFn in this case, may or may not exist, look for JSON API to decide. So, the types would look like this:

Thanks, Looking forward to these changes, sorry I din't notice the upper message.
>  so that's where those new assumptions/rules will come into play, making it a more flexible system. These changes will probably and hopefully come next week because I don't have unlimited time smile.

Thanks would like to help If I can in any way

> For your second request, yes, we are planning to extract some types, especially the ones that are referenced from the outside most like QTable's onRequest and columns definition, QSelect's onFilter, etc.

again thanks, that'll make declaring CBs easier and also if possible for large callbacks it'd be great but as far as I know, table and select have most of the bigger CBs

Thanks for your hard work

2021-11-15 19:28 UTC, engineertdog commented
I'm pretty sure this PR is what introduced a new TS error for `Promise returned in function argument where a void return was expected`.

```js
$q.dialog({
  ...options...
}).onOk(async () => {
  try {
    await someAsyncFunction();
    // do other logic after the async function.
  } catch {
    // handle error
  }
}).onCancel(async () => {
  await someAsyncFunction();
});
````

This will throw that error in `2.3.2` which was not occurring in `2.2.2`. The only way to avoid this is to mark the async function as `void` and remove `async`, or where you don't have all of the logic in a single function, use an IIFE.

2021-11-15 19:49 UTC, yusufkandemir commented
@engineertdog prior to this PR, the functions weren't even properly defined. So, yes, since it's now properly declared, you are now seeing the error. 

About the ESLint rule, please see https://typescript-eslint.io/rules/no-misused-promises#rule-details.  It suggests using an IIFE wrapper, or a named wrapper for this kind of situation. Since `onOk`, `onCancel`, etc. are basically a way to register event listeners, and we are not awaiting the return type of the handler, it doesn't make sense to make the return type `void | Promise<void>`. It may also be misleading if it's done that way. So, the type definitions are correct.

I think `checksVoidReturn` option of the rule is just making life harder without providing any significant benefits(_if it's providing any at all, at least I am not seeing it_). So, I would prefer configuring the rule to not check void returns, instead of using an IIFE, or a similar "workaround". Here is how to do it in case anyone is wondering:
```json
{
  "@typescript-eslint/no-misused-promises": [
    "error",
    {
      "checksVoidReturn": false
    }
  ]
}
```

2021-11-15 20:04 UTC, engineertdog commented
That makes sense. I appreciate the feedback and providing the fix as well.