Fix issue 11708
quasarframework/quasar pull request #11711
Opened 2021-12-16 21:30 UTC by Rolanddoda

Link to the issue: https://github.com/quasarframework/quasar/discussions/11709

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2021-12-16 21:34 UTC, rstoenescu requested changes

2021-12-16 21:34 UTC, rstoenescu commented on app/lib/webpack/create-chain.js
> +        name: `img/[path][name]${fileHash}.[ext]`
Hi,

Thanks for contributing!
Can you add `[path]` for the fonts too pls? (It's right below the images section)

2022-01-25 09:17 UTC, merged

2022-01-25 09:18 UTC, rstoenescu commented
Finally got a chance to test it out.
Thanks for contributing! This will go into next q/app.

2022-01-26 21:06 UTC, Alexssmusica commented
Good afternoon, this change caused a problem when in production, it doesn't find the files. In development it is normal.

2022-01-26 21:41 UTC, rstoenescu commented
@Alexssmusica can you provide a minimal reproduction repo pls? From our testing nothing seems to be wrong.

2022-01-26 22:11 UTC, Alexssmusica commented
It actually happens when you use these settings in quasar.conf
![image](https://user-images.githubusercontent.com/41313437/151255594-4fb0dc08-0118-4795-b94b-2bbc8e32268f.png)

2022-01-26 22:14 UTC, Alexssmusica commented
I use electron, after compiling it doesn't recognize the icons.
![image](https://user-images.githubusercontent.com/41313437/151255940-bb60fb34-3799-4605-ab84-85efb9ecadc8.png)

2022-01-26 22:17 UTC, Alexssmusica commented
And when spa this happens.
![image](https://user-images.githubusercontent.com/41313437/151256354-ab48a39e-a480-479c-8a34-28cc419a0add.png)

2022-01-26 22:20 UTC, Alexssmusica commented
In my project I went back to version 3.2.9, it worked again. These prints were a test done in the standard quasar create project.

2022-01-26 22:29 UTC, Alexssmusica commented
@rstoenescu https://github.com/Alexssmusica/test-quasar-app-3.3.0.git

2022-01-27 13:20 UTC, rstoenescu commented
Hmm, seems like it actually breaks even more use-cases. Reverted and published q/app v3.3.1

2022-01-27 16:41 UTC, Alexssmusica commented
@rstoenescu  Thanks!!!

2022-01-27 17:33 UTC, rstoenescu commented
Now need to find a way to solve the initial problem though

2022-01-28 06:30 UTC, Rolanddoda commented
@rstoenescu should you open issue #11708 after merging this?

2022-01-28 09:19 UTC, rstoenescu commented
> @rstoenescu should you open issue #11708 after merging this?

Can't reopen since it was changed into a discussion.

2022-01-28 09:41 UTC, Rolanddoda commented
@rstoenescu I see. Should I open a new issue though?

2022-01-28 10:11 UTC, rstoenescu commented
No need. I'm actively working on a solution with minimal perf impact. The last part is the hardest one.

2022-01-28 10:25 UTC, Rolanddoda commented
@rstoenescu ahh cool, good to know. Thank you and good luck with the last part

2022-01-28 13:13 UTC, rstoenescu commented
Will be available in q/app v3.3.2