[V1] Docs API Default Values are not shown. Try to fix
quasarframework/quasar pull request #12519
Opened 2022-02-18 19:31 UTC by ibrainventures

Can´t really test. Try to understand logic, .. so .. this must be the culprit. :-)

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [X] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

2022-02-18 20:22 UTC, pdanpdan requested changes

2022-02-18 20:22 UTC, pdanpdan commented on docs/src/components/DocApiEntry.js
> +          h('div', { class: 'api-row__example' }, '' + prop.default)
make this an array

2022-02-18 20:35 UTC, ibrainventures commented on docs/src/components/DocApiEntry.js
> +          h('div', { class: 'api-row__example' }, '' + prop.default)
Yah, may there is also some more wrong .. That was on my first view the difference between the working v2 docs and the not working v1 docs ..

2022-03-08 10:57 UTC, merged

2022-03-08 10:59 UTC, rstoenescu commented
Hi,

Thanks for contributing!
But you can test :) just run the docs project.
Problem was the incorrect syntax of the `h(_tag_, _opts, _children_)` where `_children_` needs to be an Array if it's not a string.