docs(cli): add example for pnpm as package manager
quasarframework/quasar pull request #12809
Opened 2022-03-15 15:34 UTC by soulsam480

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
As the new Quasar CLI is working properly with pnpm, it makes sense to mention it in the docs. This PR adds pnpm starter commands where npm and yarn are mentioned.

2022-03-15 17:03 UTC, yusufkandemir requested changes
Thanks for the contribution. It looks like none of the commands are valid, I've made some suggestions.

Aside from that, it might be "working", but it's not properly tested nor officially supported, at least not yet. It shows `Yes, use pnpm` as an answer for `Install project dependencies?`, which might be a bit misleading. But, that's because it's implemented in a generic way on project creation. The big problem is that it would not work when running commands like `quasar mode add`, `quasar new`, `quasar ext add`, etc. which are crucial. The "app core" just assumes you are using either yarn or npm, which are the only officially supported package managers. So, we can't include it on the docs.

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/convert-to-quasar-cli-with-vite.md
> +$ pnpm dx create-quasar
I guess you meant [`pnpm dlx`](https://pnpm.io/cli/dlx) and not `dx`. But, [`pnpm create`](https://pnpm.io/cli/create) would be simpler and better here:
```suggestion
$ pnpm create quasar
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/quasar-config-js.md
> +You will need the linting files already installed. If you don't know which those are, scaffold a new Quasar project folder (`yarn create quasar` or `npm init quasar` or `pnpm dx create-quasar`) and p
```suggestion
You will need the linting files already installed. If you don't know which those are, scaffold a new Quasar project folder (`yarn create quasar` or `npm init quasar` or `pnpm create quasar`) and pick "Linting" when asked about it.
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-webpack/convert-to-quasar-cli-with-webpack.md
> +$ pnpm dx create-quasar
```suggestion
$ pnpm create quasar
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +$ pnpm dx create-quasar
```suggestion
$ pnpm create quasar
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +    $ pnpm dx create-quasar
```suggestion
    $ pnpm create quasar
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +$ pnpm global add @quasar/cli
There is no such thing as `pnpm global`, it should be [`pnpm add -g` or `pnpm add --global`](https://pnpm.io/cli/add#--global--g). It's a mix between `npm`(`-g`) and `yarn`(`add`) 🙂

```suggestion
$ pnpm add -g @quasar/cli
```

2022-03-15 17:03 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +    $ pnpm global add @quasar/cli
```suggestion
    $ pnpm add -g @quasar/cli
```

2022-03-15 17:28 UTC, soulsam480 commented on docs/src/pages/quasar-cli-vite/convert-to-quasar-cli-with-vite.md
> +$ pnpm dx create-quasar
Aah yes yes. Will change those. I never tried to run with pnpm create quasar, so it was a mistake from my side. Let me change those.

2022-03-15 17:30 UTC, soulsam480 commented
I hope the team has some plan to support pnpm considering its speed and efficiency.

2022-03-15 17:30 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/convert-to-quasar-cli-with-vite.md
> +$ pnpm dx create-quasar
Fyi, you can easily commit suggestions by using the button.
![image](https://user-images.githubusercontent.com/6266078/158436782-87668366-3efe-4e8c-a11f-7485b0694670.png)

2022-06-05 21:12 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +
There is now a tip section called "Requirements" above this. It says "Yarn v1 (strongly recommended) or NPM."

![image](https://user-images.githubusercontent.com/6266078/172070791-e87df6f6-b928-43c1-889f-c1ad84df7c4c.png)

Please also update it accordingly.

2022-09-09 14:15 UTC, merged

2022-09-09 14:18 UTC, yusufkandemir commented on docs/src/pages/start/quasar-cli.md
> +
I ended up adding this myself into this PR.

2022-09-09 14:20 UTC, yusufkandemir commented
Thanks for the contribution again.