feat(create-quasar): Add <script setup> option for TS
quasarframework/quasar pull request #13949
Opened 2022-07-13 20:01 UTC by AnJ-Github

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

This PR introduces a new option inside Quasar CLI for initializing a project with [`<script setup>`](https://vuejs.org/api/sfc-script-setup.html) syntax:
```js
choices: [
  { title: 'Composition API with <script setup>', value: 'composition-setup', description: 'recommended' },  // <- NEW CHOICE
  { title: 'Composition API', value: 'composition' },
  { title: 'Options API', value: 'options' },
  { title: 'Class-based', value: 'class', description: 'DEPRECATED; see https://github.com/quasarframework/quasar/discussions/11204', disabled: true }
]
```

Currently only TypeScript projects are supported (both Vite and Webpack). Javascript does not have this prompt implemented (Options vs Composition etc.).
There is also a small note added about `<script setup>` inside the documentation.

`src/pages/IndexPage.vue` as an example:

**Previously:**
```vue
<script lang="ts">
import { Todo, Meta } from 'components/models';
import ExampleComponent from 'components/ExampleComponent.vue';
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'IndexPage',
  components: { ExampleComponent },
  setup () {
    const todos = ref<Todo[]>([
      // ...
    ]);
    const meta = ref<Meta>({
      totalCount: 1200
    });
    return { todos, meta };
  }
});
</script>
```

**After PR:**
```vue
<script setup lang="ts">
import { Todo, Meta } from 'components/models';
import ExampleComponent from 'components/ExampleComponent.vue';
import { ref } from 'vue';

const todos = ref<Todo[]>([
 // ...
]);
const meta = ref<Meta>({
  totalCount: 1200
});
</script>
```

2022-07-14 08:54 UTC, yusufkandemir requested changes
Thanks for contributing 👏 I made a few suggestions.

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/EssentialLink.vue
> +})<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
Let's use TS-specific features to simplify the code.
```suggestion
export interface EssentialLinkProps {
  title: string;
  caption?: string;
  link?: string;
  icon?: string;
}
const props = withDefaults(defineProps<EssentialLinkProps>(), {
  link: '#',
});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/ExampleComponent.vue
> +  clickCount.value += 1
```suggestion
  clickCount.value += 1;
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/ExampleComponent.vue
> +})
```suggestion
import { computed, ref } from 'vue';
import { Todo, Meta } from './models';

interface Props {
  title: string;
  todos?: Todo[];
  meta: Meta,
  active: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  todos: () => [],
});
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/EssentialLink.vue
> +
Let's remove the extra empty line.
```suggestion
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/layouts/MainLayout.vue
> +const essentialLinks = [
```suggestion
import EssentialLink, { EssentialLinkProps } from 'components/EssentialLink.vue';

const essentialLinks: EssentialLinkProps[] = [
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/EssentialLink.vue
> +
```suggestion
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/EssentialLink.vue
> +})<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
Let's use TS-specific features to simplify the code.
```suggestion
export interface EssentialLinkProps {
  title: string;
  caption?: string;
  link?: string;
  icon?: string;
}
const props = withDefaults(defineProps<EssentialLinkProps>(), {
  link: '#',
});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/ExampleComponent.vue
> +})
```suggestion
import { computed, ref } from 'vue';
import { Todo, Meta } from './models';

interface Props {
  title: string;
  todos?: Todo[];
  meta: Meta,
  active: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  todos: () => [],
});
```

2022-07-14 08:54 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/ExampleComponent.vue
> +  clickCount.value += 1
```suggestion
  clickCount.value += 1;
```

2022-07-14 08:54 UTC, yusufkandemir commented on docs/src/pages/start/how-to-use-vue.md
> +
```suggestion
```

2022-07-14 08:54 UTC, yusufkandemir commented on docs/src/pages/start/how-to-use-vue.md
> +But you can still use syntax without `setup` if you wish. The only difference is within the `<script>` tag.
```suggestion
But you can still use Composition API without `<script setup>` or Options API if you wish. The only difference is within the `<script>` tag.
```

2022-07-14 08:54 UTC, yusufkandemir commented on docs/src/pages/start/how-to-use-vue.md
> +Currently it is recommended to use `<script setup>` syntax. Check out [VueJS documentation](https://vuejs.org/api/sfc-script-setup.html) for more information.
```suggestion
Currently, it is recommended to use Composition API with `<script setup>`. Check out [Vue.js documentation](https://vuejs.org/api/sfc-script-setup.html) for more information.
```

2022-07-14 09:05 UTC, Random-nobody commented
> Thanks for contributing 👏 I made a few suggestions.

@yusufkandemir  Thank you for your suggestions. I was thinking about them as well. But I decided to make minimal change to the source code and just introduce new option, without altering props or fixing small code formatting inconsistencies. But if you think that this is fine to be in a single PR I will go ahead and accept them 👍

2022-07-14 09:23 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/ExampleComponent.vue
> +  meta: Meta,
A mistake from my previous suggestion.
```suggestion
  meta: Meta;
```

2022-07-14 09:23 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/ExampleComponent.vue
> +  meta: Meta,
A mistake from my previous suggestion.
```suggestion
  meta: Meta;
```

2022-07-19 08:56 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/components/EssentialLink.vue
> +});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
Changes to my previous suggestions:
`props` variable isn't used, so we should remove the assignment. Also, the vue3-recommended ruleset complains because we specify a default for some optional props and didn't for others. It would be a better idea to match the old structure anyway.

```suggestion
withDefaults(defineProps<EssentialLinkProps>(), {
  caption: '',
  link: '#',
  icon: '',
});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
```

2022-07-19 08:59 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/BASE/src/components/EssentialLink.vue
> +});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
See https://github.com/quasarframework/quasar/pull/13949#discussion_r924241462
```suggestion
withDefaults(defineProps<EssentialLinkProps>(), {
  caption: '',
  link: '#',
  icon: '',
});<% } else if (typescriptConfig === 'composition') { %><script lang="ts">
```

2022-07-19 09:52 UTC, yusufkandemir approved these changes

2022-07-19 11:30 UTC, yusufkandemir commented on create-quasar/templates/app/quasar-v2/ts-webpack/index.js
> +        { title: 'Composition API', value: 'composition' },
As `<script setup>` is not yet widely used in our docs, let's make it the second option. But, let's add `recommended` to both. So, people who know <script setup> will not get confused about why it's not recommended, and those who don't know it continues with the non-script setup which is widely used in the docs, examples, etc. and they don't get stuck. When we update the docs to address that, we might consider switching the order or the recommendations.

```suggestion
        { title: 'Composition API', value: 'composition', description: 'recommended' },
        { title: 'Composition API with <script setup>', value: 'composition-setup', description: 'recommended' },
```

2022-07-20 08:14 UTC, merged

2022-07-20 08:15 UTC, yusufkandemir commented
Thanks for your contribution and time 👏