Doc(app-vite & app-webpack): accessing router in store
quasarframework/quasar pull request #14079
Opened 2022-07-28 11:31 UTC by rashidpathiyil

### Documented accessing router in stores

**What kind of change does this PR introduce?** 

- [x] Documentation

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

Ref #14068

2022-07-28 19:17 UTC, yusufkandemir requested changes
Nice 👏 Finally, some documentation for this feature! Made some small suggestions.

2022-07-28 19:17 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/state-management-with-pinia.md
> +Simply use `this.router` in Pinia stores to get access to the router.
Let's leave an empty line after the title for readability(_codebase-wise_) and to match with the other usages.

Let's update the title slightly.

```suggestion
## Accessing the router in Pinia stores

Simply use `this.router` in Pinia stores to get access to the router.
```

2022-07-28 19:17 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/state-management-with-pinia.md
> +
This is not clear enough and redundant as you have a better example below that.
```suggestion
```

2022-07-28 19:17 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/state-management-with-vuex.md
> +Simply use `this.$router` in Vuex stores to get access to the router.
```suggestion
## Accessing the router in Vuex stores

Simply use `this.$router` in Vuex stores to get access to the router.
```

2022-07-28 19:17 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-webpack/state-management-with-pinia.md
> +```
Combined suggestion from the Vite page above.
```suggestion
## Accessing the router in Pinia stores

Simply use `this.router` in Pinia stores to get access to the router.
```

2022-07-28 19:17 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-webpack/state-management-with-vuex.md
> +```
Combined suggestion from the Vite page above.
```suggestion
## Accessing the router in Vuex stores

Simply use `this.$router` in Vuex stores to get access to the router.
```

2022-07-28 19:57 UTC, rashidpathiyil commented
> Nice 👏 Finally, some documentation for this feature! Made some small suggestions.

✅ Done @yusufkandemir

2022-07-28 20:22 UTC, yusufkandemir approved these changes

2022-07-29 04:57 UTC, smolinari requested changes
If you could, please update the "See an example..." sentences to the suggested changes. 

Thanks for your contribution!!! :+1:

2022-07-29 04:57 UTC, smolinari commented on docs/src/pages/quasar-cli-vite/state-management-with-pinia.md
> +See an example of accessing router in Pinia store action:
I'd say "Here is an example" here or just remove this line as is on the other pages.

2022-07-29 04:57 UTC, smolinari commented on docs/src/pages/quasar-cli-vite/state-management-with-vuex.md
> +See an example of accessing router in Vuex store:
Same here. Use "This is an example....".... or "Here is an example....".

2022-07-29 04:57 UTC, smolinari commented on docs/src/pages/quasar-cli-webpack/state-management-with-pinia.md
> +See an example of accessing router in Pinia store action:
And again.

2022-07-29 04:57 UTC, smolinari commented on docs/src/pages/quasar-cli-webpack/state-management-with-vuex.md
> +See an example of accessing router in Vuex store:
Last one.

2022-07-29 05:40 UTC, rashidpathiyil reviewed
Updated sentences as per your suggestion. @smolinari

2022-07-29 05:49 UTC, smolinari approved these changes

2022-07-29 07:59 UTC, yusufkandemir commented on docs/src/pages/quasar-cli-vite/state-management-with-vuex.md
> +
```suggestion
```

2022-07-29 08:08 UTC, merged