Fix `currentIndex` calculation
quasarframework/quasar pull request #15404
Opened 2023-02-07 15:21 UTC by tvogel

For some reason, `selected` and `computedRows` do not contain the same objects, so `indexOf()` always fails. Locating the correct entry by `id` however works. Is `computedRows` rebuilt under the hood with new objects?

**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
I did not look for existing bug reports. I found the example not to work with Firefox 108.0.2 (64-Bit) on openSUSE Tumbleweed, so I debugged it in https://codepen.io/eijk/pen/RwBOdbm and found this change to restore keyboard navigation.

2023-02-07 16:04 UTC, pdanpdan requested changes
Please add `toRaw` here

2023-02-07 16:09 UTC, pdanpdan commented
Please make some changes:

- import `toRaw` from vue
- convert the line you changed to `const currentIndex = selected.value.length > 0 ? computedRows.indexOf(toRaw(selected.value[ 0 ])) : -1`
- please also add a small fix - after line 196 (inside the nextTick, as a last line) add `tableRef.value.$el.focus()` to refocus the table when changing pages

2023-02-07 16:20 UTC, tvogel commented
Thanks! Used your suggestions. Only, I don't understand the third change because it does not seem to make a difference on Firefox!?

2023-02-07 16:23 UTC, pdanpdan commented
When you are on a last/first item in a page and navigate to next/previous page (arrow down/up) then the element that had focus is removed and sometimes the table loses focus so the next keypress will not be caught

2023-02-07 16:26 UTC, tvogel commented
OK, never happened to me while I played with it.

2023-02-14 09:35 UTC, merged

2023-02-14 09:35 UTC, rstoenescu commented
Thanks for contributing!