feat(create-quasar): add git repo automatic initialization
quasarframework/quasar pull request #15629
Opened 2023-03-27 15:20 UTC by Nike682631

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

2023-03-27 16:27 UTC, IlCallo requested changes
Nice, I tested it out and it seems to work for all type of project which can be generated via `create-quasar`

2023-03-27 16:27 UTC, IlCallo commented on create-quasar/utils/index.js
> +    );
If you check out `exec` import at the top of the file, you can see that it's actually an alias for `execSync`, so everything is sync and `async/await` isn't needed

2023-03-27 16:27 UTC, IlCallo commented on create-quasar/utils/index.js
> +function hasGit() {
Nice adaptation, but I'd keep all these git-related utils in a separate file in the `utils` folder, since this file is already quite long.
You can re-export `initializeGit` from this index file then

2023-03-28 09:56 UTC, IlCallo approved these changes

2023-04-04 01:53 UTC, dongwa commented on create-quasar/utils/index.js
> +      "git commit -m 'Initialize the project 🚀' --no-verify",
I think there should be a change to `git commit -m 'chore: Initialize the project 🚀`, because 'Conventional Commit' is popular.

2023-04-04 11:11 UTC, IlCallo commented on create-quasar/utils/index.js
> +      "git commit -m 'Initialize the project 🚀' --no-verify",
It's not that important for the initial commit, and not everybody is using conventional commits

2023-04-26 09:57 UTC, rstoenescu requested changes

2023-04-26 09:57 UTC, rstoenescu commented on create-quasar/utils/git.js
> +    logger.warning(
There is no `logger` imported here.

2024-08-01 11:32 UTC, rstoenescu commented
Pushed separate commit. Too many merge errors & made the new approach simpler (and re-using more of the current create-quasar utils).

2024-08-01 11:32 UTC, closed without merging

2024-08-01 14:51 UTC, IlCallo commented
@rstoenescu you forgot this check, which is extremely important for any kind of monorepo setup

https://github.com/quasarframework/quasar/pull/15629/files#diff-8a918d211b57fb292786103000579687e6afb79d6438799a78ad4a60e01e15d9R14-R21
https://github.com/quasarframework/quasar/pull/15629/files#diff-8a918d211b57fb292786103000579687e6afb79d6438799a78ad4a60e01e15d9R31-R36

If you run `git init` within a subfolder of a git repo, it doesn't error out, so the `try/catch` you used won't catch that

Running `git status` is the way to detect if you're already into a git repository and avoid initializing a nested one by mistake