Update font awesome instructions when using Kits
quasarframework/quasar pull request #16099
Opened 2023-07-20 11:26 UTC by gregveres

I have added information on using Font Awesome Pro Kits. In my opinion, this is the way to go when using Font Awesome Pro since it allows you to define a collection of icons that only include icons you use in your project. 

I also included a couple of other tips I wish were written down when I was learning how to use Font Awesome in Quasar. 

If this information was in this doc, it would have saved me at least  3/4 of a day figuring it all out for myself and pestering people on discord.

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [ ] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

2023-07-31 09:36 UTC, rstoenescu requested changes
Hi,

Thank you for contributing!
I think it would be better if the two ways are separated. Some of the steps are not required when using Kits, so it'll only confuse someone reading the guide.

Can you please make a separate guide for the Kits?

2023-07-31 11:26 UTC, gregveres commented
Should it be a different page, or a different guide on the same page (say below the existing Font Awesome Pro section)?

2023-08-05 13:33 UTC, gregveres commented
@rstoenescu I have updated the document file to split out the Kit instructions. There is now a section for non-kit installation and a section for kit installation.

2026-08-19 07:26 UTC, rstoenescu commented
Hi Greg, thank you again for putting this together, and apologies that it sat for so long. The docs page has since moved on to Fontawesome v7, so rather than asking you to rebase a two-year-old branch, we've adapted your material to the current page in #18516: the Kits section, the whole-icon-set replacement example, plus a note that a subsetted kit must include the Light style icons the `fontawesome-v7-pro` icon set references. The npm token / `@fortawesome/fontawesome-pro` install steps were dropped from the Kits flow since a self-hosted kit download does not need them. Closing this one in favor of #18516. Your write-up saved the next person that 3/4 of a day you mentioned, much appreciated!

2026-08-19 07:26 UTC, closed without merging