feat(create-quasar): add TS AE template
quasarframework/quasar pull request #17168
Opened 2024-05-06 09:33 UTC by yusufkandemir

**What kind of change does this PR introduce?**

- Feature

**Does this PR introduce a breaking change?**

- No

**The PR fulfills these requirements:**

- It's submitted to the `dev` branch (or `v[X]` branch)

**Other information:**
Contains fixes for app-vite&app-webpack types of AE API files, e.g. IndexAPI

Adds a TS AE template, highlights:
- TypeScript setup, of course
- ESLint v9 using flat config format, with a good configuration (_ESLint v9 will be backported to all other relevant templates later_)
- Vue SFC (.vue files) support (_will be backported to the JS template later_)
- Monorepo structure with app-vite and app-webpack playground apps

There is a limitation with the SFC support. When using `<script setup lang="ts">`, it won't work in JS app-webpack apps. This is because as mkdist skips processing it and there is no TypeScript support in JS app-webpack, so it fails. If https://github.com/unjs/mkdist/pull/210 gets released, then this limitation will become "when using `<script setup lang="ts">` AND type-only macros, e.g. `defineProps<QBtnProps>()`.
Alternatively, to completely eliminate the limitation, we could add TS processing support to app-webpack when using JS. We may do this in the core, or via a snippet in AE index API. app-vite JS works fine due to how Vite is configured to handle TS automatically.
For now, I just left some comments explaining the limitations.

2024-08-08 11:05 UTC, IlCallo requested changes
`.gitignore` file is missing into `templates/app-extension/ae-ts/BASE`

Example content:
```ini
.DS_Store
.thumbs.db
node_modules
dist

# Log files
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor directories and files
.idea
*.suo
*.ntvs*
*.njsproj
*.sln
```
This is important since we now auto-initialize a Git repo when the scaffolding completes

---

Latest commits and in general some `package.json` lines assume the dev will be using `pnpm`

E.g. `workspace:*` would break installation with `npm` and `yarn`
For `npm` it seems that using `^0.0.1` would be fine to get past deps installation, I couldn't find a way to say "just take the latest available in the repository"

I haven't tested this with Bun

**This needs to be fixed before merging**

Btw, I simulated the usage of different package managers with this command, to get `runningPackageManager` filled in with some actual values

`npm_config_user_agent=npm/10.5.0 node <path-to-quasar-folder>/quasar/create-quasar/index.js`

---

I haven't explored how hard it would be to implement this, but we should explore at some point running the root level `format` command after deps installation but before linting
This should probably be done automatically and for all `create-coralloy` templates, if a `format` script actually exists, without an option to let the user choose

---

I went ahead, rebased the PR and fixed a couple of my own comments in my local copy
If you're ok with it, I can force-push the rebase and my commits for you

---

If [this](https://github.com/unjs/mkdist/pull/210) is fixed, I can ping Daniel about it and see if we can get it in

---

When running the AE `build` command, I got a warning from `mkdist` about installing `vue-tsc` to get proper typings for components, or something similar
Are you aware of it?

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/_eslint.config.js
> +import globals from 'globals';
`globals` package hasn't been installed, causing a TS error at this import
Tested using `pnpm`
Adding it as a dev dependecy solves the problem

Apparently it has been removed from ESLint since v9 and is meant to be installed manually when needed: [eslint.org/docs/latest/use/configure/language-options#predefined-global-variables](https://eslint.org/docs/latest/use/configure/language-options#predefined-global-variables)

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/_eslint.config.js
> +import { version as vueVersion } from 'vue';
`vue` package hasn't been installed at root level, causing a TS error at this import

This can be solved by
- using `shamefully-hoist` option into a `.npmrc` file at root level
- removing vue dependency into the 3 packages of the monorepo and add it at root level

I tested both solutions with `pnpm` and `npm`
Unluckily the second one doesn't work for `npm` (of course), so I'd go with the first one
I haven't tested it with `yarn` and `bun`

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/_package.json
> +    "typescript-eslint": "^7.8.0"
A new release of `typescript-eslint` is out which supports ESLint 9
Using v7 triggers a peerDeps warning when installing

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/README.md
> +pnpm install
Shouldn't the package manager here be dynamically filled in instead of hardcoded to `pnpm`?

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_package.json
> +    "<%= pkgName %>": "workspace:*",
Does this work with `npm` and `yarn` too?
Isn't `workspace:*` a `pnpm` thing?

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_tsconfig.json
> +  "extends": "../../tsconfig.json",
Any reason for not using `@quasar/app-vite/tsconfig-preset`?
I tried it out and it worked like a charm, slimming the file down considerably

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/src/quasar.d.ts
> +/// <reference types="<%= pkgName %>" />
I'd add a comment about this line too, it may not be that clear to newcomers

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/README.md
> +pnpm install
Shouldn't this use the package manager name chosen by the user?

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/_package.json
> +    "<%= pkgName %>": "workspace:*",
Does this syntax work with `npm` and `yarn` too?

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/_tsconfig.json
> +  "extends": "../../tsconfig.json",
Any reason for not using `@quasar/app-webpack/tsconfig-preset`?
I tried it out and it worked like a charm, slimming the file down considerably

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/postcss.config.cjs
> +// https://github.com/michael-ciniawsky/postcss-load-config
This requires a `/* eslint-disable */` as other config files, otherwise linting will fail due to `require` usage

2024-08-08 11:05 UTC, IlCallo commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/src/quasar.d.ts
> +/// <reference types="<%= pkgName %>" />
I'd add a comment on this one too, to explain it to TS newbies

2024-08-08 11:19 UTC, IlCallo commented
Check out latest commits in this branch, where I pushed some fixes for the problems I highlighted
https://github.com/IlCallo/quasar/tree/ae-ts-fixes

2024-08-09 16:22 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/postcss.config.cjs
> +// https://github.com/michael-ciniawsky/postcss-load-config
The ignore patterns were incorrect. I've adjusted it to address this.

2024-08-09 16:24 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_package.json
> +    "<%= pkgName %>": "workspace:*",
I don't think so. The template was pnpm only at first. It seems I've overlooked this part. I will think about it and do some research. yarn v1 should auto-link them. Not sure how npm does it. Should be solvable with some if-else rendering.

2024-08-09 16:24 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/README.md
> +pnpm install
Yes, will do

2024-08-09 16:25 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/_package.json
> +    "typescript-eslint": "^7.8.0"
It was updated, but not have been pushed yet at the time of your comment. All the packages have been updated.

2024-08-09 16:26 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/_eslint.config.js
> +import { version as vueVersion } from 'vue';
I've gone with the first way.

2024-08-09 16:27 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/_eslint.config.js
> +import globals from 'globals';
Already installed, but wasn't pushed at the time of your comment.

2024-08-09 16:30 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_tsconfig.json
> +  "extends": "../../tsconfig.json",
It's for re-using the root config. There is no way to extend both. The root config shouldn't be special now, so we could use the app-vite preset. If the users greatly customize their tsconfigs, they could update it back to point to the root config, if needed. I'll see what the differences would be and decide.

2024-08-09 16:31 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/src/quasar.d.ts
> +/// <reference types="<%= pkgName %>" />
That's a good idea. I should also add it to the AE installation instructions. That way, the users who will install the AE can also benefit from the global component types.

2024-08-09 16:32 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/README.md
> +pnpm install
Yes, will do

2024-08-09 16:32 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/_package.json
> +    "<%= pkgName %>": "workspace:*",
Resolving in favor of the app-vite one

2024-08-09 16:32 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/_tsconfig.json
> +  "extends": "../../tsconfig.json",
Resolving in favor of the app-vite one

2024-08-09 16:32 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/src/quasar.d.ts
> +/// <reference types="<%= pkgName %>" />
Resolving in favor of the app-vite one

2024-08-09 16:59 UTC, yusufkandemir commented
> I went ahead, rebased the PR and fixed a couple of my own comments in my local copy
If you're ok with it, I can force-push the rebase and my commits for you

I already had rebased it and made some changes. They were waiting locally. So, I force-pushed them instead. Thanks. I will check the changes for other bits that I haven't addressed.

> If https://github.com/unjs/mkdist/pull/210 is fixed, I can ping Daniel about it and see if we can get it in

I've done it myself, thanks.

> Btw, I simulated the usage of different package managers with this command, to get runningPackageManager filled in with some actual values
> npm_config_user_agent=npm/10.5.0 node <path-to-quasar-folder>/quasar/create-quasar/index.js

Just FYI, `pnpm node .../index.js`, `yarn node .../index.js`, etc. also work, while inside a directory with package.json.

> When running the AE build command, I got a warning from mkdist about installing vue-tsc to get proper typings for components, or something similar
Are you aware of it?

It's a recent change. I've noticed it recently, after returning for the final touches. Installing it didn't make any difference for the test component. But, I'll add vue-tsc to the template, to avoid the warning and just in case.

> I haven't explored how hard it would be to implement this, but we should explore at some point running the root level format command after deps installation but before linting

We used to run the format script, but probably after listing. It was probably a very long time ago. Maybe it was lost while migrating from starter-kit to create-quasar. It wasn't really hard to do so. Running it after linting is better, when ESLint auto-fixes some stuff. For example, if there is an unused eslint-disable comment, ESLint removes the comment, leaving the line empty. Running the format script afterward, clean up those empty lines, and adjust other styles if needed. Do you have any reason why do you want to run linting before formatting?

2024-08-12 10:18 UTC, IlCallo commented
> Do you have any reason why do you want to run linting before formatting?

Honestly, your reasoning makes much more sense than my own thoughts
I probably remember wrong and linting > formatting is the correct order

2024-08-26 16:39 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-webpack/README.md
> +pnpm install
done

2024-08-26 16:39 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_tsconfig.json
> +  "extends": "../../tsconfig.json",
done

2024-08-26 16:39 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/_package.json
> +    "<%= pkgName %>": "workspace:*",
done

2024-08-26 16:39 UTC, yusufkandemir commented on create-quasar/templates/app-extension/ae-ts/BASE/playground/quasar-cli-vite/README.md
> +pnpm install
done

2024-08-26 17:36 UTC, IlCallo approved these changes

2024-09-04 10:14 UTC, rstoenescu commented
AE, TS, PNPM:
![image](https://github.com/user-attachments/assets/b8829995-c2d7-4792-b5ab-ee18d717970f)

2024-09-04 10:20 UTC, rstoenescu commented
AE, TS, Yarn:

![image](https://github.com/user-attachments/assets/9d321ab2-db45-4b07-bbbb-1620e64e7f04)

1. "To get started" section is wrong. We'll need some custom code.
2. Picked yarn and still having pnpm stuff (pnpm-workspace, package.json > scripts > pnpm commands)

2024-09-04 10:32 UTC, rstoenescu requested changes
Posted two comments earlier

2024-09-04 10:37 UTC, yusufkandemir commented
@rstoenescu

Regarding the instructions for getting started in the CLI message, I'll check it out.

The package manager stuff is like that because it uses the detected package manager to scaffold stuff accordingly. The selection only happens after the scaffolding is complete, so we can't use it with how the code is structured now. `pnpm create`, `npm init`, etc. should all detect the package manager fine. The only case I can find is running the script directly via Node. So, in practice, I think it's fine.

So, do you think we should leave it as is? Should I rework how package manager selection happens to scaffold stuff accordingly? Should I do something else?

2024-09-12 16:31 UTC, IlCallo commented
Quoting from my first comment

> Btw, I simulated the usage of different package managers with this command, to get runningPackageManager filled in with some actual values
> `npm_config_user_agent=npm/10.5.0 node <path-to-quasar-folder>/quasar/create-quasar/index.js`

Use this to test out how users will actually experience this

2024-11-08 20:20 UTC, merged