Update Dark.js
quasarframework/quasar pull request #17670
Opened 2024-12-01 14:30 UTC by diadal

this helps to know if the device is in dark mode or not

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ *] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [* ] No

**The PR fulfills these requirements:**

- [ dev] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

2024-12-02 14:42 UTC, rstoenescu requested changes
Hi,

Thank you for contributing!
Please take a look at my comments. Would help with it, but I have no bandwidth for it at the moment.

You can test with "pnpm dev:ssr" and "pnpm dev" in /ui.
When you're ready, a "pnpm build" without errors would ensure it passes the shallow validation for JSON also.

2024-12-02 14:42 UTC, rstoenescu commented on ui/src/plugins/dark/Dark.js
> +    Plugin.isEnabled = matchMedia.matches
`isPreferred` would be better otherwise it is confusing

2024-12-02 14:42 UTC, rstoenescu commented on ui/src/plugins/dark/Dark.js
> +      this.isEnabled = matchMedia.matches
There is no matchMedia here, nor can it be. This code runs on the server. It should be defaulted to a value (probably `false`) and updated only on client takeover, otherwise there will be hydration errors.

2024-12-02 14:42 UTC, rstoenescu commented on ui/src/plugins/dark/Dark.js
> +  isEnabled: false,
Should be added to Dark.json too.

2024-12-02 16:24 UTC, diadal commented on ui/src/plugins/dark/Dark.js
> +    Plugin.isEnabled = matchMedia.matches
ok i will update this

2024-12-02 16:25 UTC, diadal commented on ui/src/plugins/dark/Dark.js
> +      this.isEnabled = matchMedia.matches
noted

2024-12-02 16:25 UTC, diadal commented on ui/src/plugins/dark/Dark.js
> +  isEnabled: false,
I did that on but i will update  it to isPreferred

2026-03-03 20:02 UTC, yusufkandemir commented
Closing as #17672 seems to be the updated version of this.

2026-03-03 20:02 UTC, closed without merging