feat(quasar): add `quasar docs` command
quasarframework/quasar pull request #4045
Opened 2019-05-04 21:06 UTC by lucasfernog

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

The ```quasar docs``` command receives a Quasar component/directive/plugin and opens the docs page. It also supports app extensions (however, i did not test it). It also has a --api option, which uses the API table anchor as URL.

Credits to @hawkeye64 for the idea.

2019-05-04 21:43 UTC, nothingismagick commented
Wow. Congrats on this!!! Great job

2019-05-04 21:46 UTC, lucasfernog commented
Thanks. Will adjust it to support ```quasar docs components/plugins/directives```.

2019-05-04 22:04 UTC, nothingismagick commented
Just a dumb question: how hard would it be to have

$ quasar api search ${search_term}

2019-05-04 22:13 UTC, lucasfernog commented
> Just a dumb question: how hard would it be to have $ quasar api search ${search_term}

That's a VERY nice idea, and not hard at all. Just a matter of reading all API file names (quasar/dist/api/*.json) and string filtering them. If it will be another command, I can make another PR.

2019-05-04 22:14 UTC, nothingismagick commented
Oh please, do it.

On Sun, 5 May 2019, 00:13 Lucas Fernandes Nogueira, <
notifications@github.com> wrote:

> Just a dumb question: how hard would it be to have $ quasar api search
> ${search_term}
>
> That's a VERY nice idea, and not hard at all. Just a matter of reading all
> API file names (quasar/dist/api/*.json) and string filtering them. If it
> will be another command, I can make another PR.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/quasarframework/quasar/pull/4045#issuecomment-489369570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIM4G6AYSEDHOFXRIWKGEWLPTYDAZANCNFSM4HKZYORA>
> .
>

2019-05-04 22:49 UTC, lucasfernog commented
Another thing that is missing here: can this command read the Quasar build config and get the user preferred browser? I've tried but couldn't do it.

2019-05-06 01:54 UTC, lucasfernog commented
> Another thing that is missing here: can this command read the Quasar build config and get the user preferred browser? I've tried but couldn't do it.

Fixed with latest commits. Also fixed running with app extension API. This PR is now done unless you want something else.

2019-05-13 17:58 UTC, lucasfernog commented
TODO: move default "docs" values to the build command.

2019-11-26 13:34 UTC, rstoenescu requested changes

2019-11-26 13:34 UTC, rstoenescu commented on app/bin/quasar
> +  'docs',
now obsolete

2019-11-26 13:34 UTC, rstoenescu commented on app/bin/quasar-describe
> +  }
Would be good to move this after the switch(). In case it fails it should at least print out the API.

2019-11-26 13:34 UTC, rstoenescu commented on docs/src/components/DocApi.vue
> +    parseJson (name, { type, behavior, docs, ...api }) {
It should be "meta" instead of "docs"

2019-11-26 13:34 UTC, rstoenescu commented on docs/src/pages/quasar-cli/cli-documentation/commands-list.md
> +
Now obsolete. To remove.

2019-11-26 13:34 UTC, rstoenescu commented on ui/build/build.api.js
> +    props: [ 'docsRoute', 'docsPage', 'docsApiAnchor' ],
Let's use one prop only "docsUrl" with full URL. For now, point to `https://v1.quasar.dev`. Example:

```js
meta: {
  docsUrl: 'https://v1.quasar.dev'
}
```

2019-11-26 13:34 UTC, rstoenescu commented on ui/src/components/btn/QBtn.json
> +      "examples": [23],
More space around is generally better for the eyes. Not important though, but I see this change everywhere.

2019-11-26 13:34 UTC, rstoenescu commented on ui/src/components/pagination/QPagination.json
> +        "docsPage": {
Find & replace failing :)

2019-11-26 13:34 UTC, rstoenescu commented on ui/src/components/table/QTable.json
> +        "docsPage": {
Find & replace failing :)
Same for all others here.

2019-11-26 13:34 UTC, rstoenescu commented on app/bin/quasar-describe
> +  if (apiParts.docs) {
"apiParts.docs" ?
Also, make it fail-safe. If it doesn't have the meta.docsUrl, then don't try to open it. The API files with the meta field will only be available in upcoming quasar v1.5.0+ only.

2019-11-26 14:55 UTC, merged