Added more description to the spacing documentation
quasarframework/quasar pull request #5603
Opened 2019-11-15 14:11 UTC by InfoSec812

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Resolves #5601

2019-11-15 14:25 UTC, pdanpdan commented
This looks very nice, thank you.

2019-11-15 14:27 UTC, pdanpdan requested changes
Please remove `(ONLY for specific margins: q-ml-*, q-mr-*, q-mx-*)` from all rows and check to only show `auto` for all `q-p...` and `q-ml-...`, `q-mr-...` and `q-mx-...`

2019-11-15 16:39 UTC, InfoSec812 commented
> Please remove `(ONLY for specific margins: q-ml-*, q-mr-*, q-mx-*)` from all rows and check to only show `auto` for all `q-p...` and `q-ml-...`, `q-mr-...` and `q-mx-...`

@pdanpdan I think that this should be corrected

2019-11-15 17:00 UTC, pdanpdan requested changes

2019-11-15 17:00 UTC, pdanpdan commented on docs/src/pages/style/spacing.md
> -| `q-` | `m` (margin) | `x` (left & right) | `auto` (ONLY for specific margins: q-ml-*, q-mr-*, q-mx-*) | `q-mx-auto` |
This should stay (without comment)

2019-11-15 17:00 UTC, pdanpdan commented on docs/src/pages/style/spacing.md
> -| `q-` | `m` (margin) | `l` (left) | `auto` (ONLY for specific margins: q-ml-*, q-mr-*, q-mx-*) | `q-ml-auto` |
This should stay (without comment)

2019-11-15 17:00 UTC, pdanpdan commented on docs/src/pages/style/spacing.md
> -| `q-` | `m` (margin) | `r` (right) | `auto` (ONLY for specific margins: q-ml-*, q-mr-*, q-mx-*) | `q-mr-auto` |
This should stay (without comment)

2019-11-18 12:26 UTC, merged

2019-11-18 12:26 UTC, rstoenescu commented
Thank you for contributing!