docs(ssr): Added deploying instructions
quasarframework/quasar pull request #7897
Opened 2020-10-14 10:08 UTC by MrKappa

Added deploying instructions for production scenario using Nginx as reverse proxy

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2020-10-14 17:23 UTC, IlCallo requested changes

2020-10-14 17:23 UTC, IlCallo commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +For serving our Quasar SSR web app in the real world we should consider using Nginx as reverse proxy for leveraging these advantages:
All documentation is based on using "you"/"your" instead of "we"/"our"

2020-10-14 17:23 UTC, IlCallo commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +Remember to run node with NODE_ENV=production
Why is this needed? What happens if you don't

2020-10-14 17:23 UTC, IlCallo commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +## Production scenario
I'd rename as "Usage with Nginx" instead: there may be many "production scenarios"

2020-10-14 17:45 UTC, outofmemoryagain commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +For serving our Quasar SSR web app in the real world we should consider using Nginx as reverse proxy for leveraging these advantages:
Technical writing typically avoids using 1st and 2nd person.  For that reason I would consider changing to be something along the lines of:
"Consider using a reverse proxy, such as Nginx, when hosting a Quasar SRR web app in the real world.  The following are just some of the potential benefits:"

2020-10-14 17:53 UTC, outofmemoryagain commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +You may have to consider the scope of your web app, the average number of requests and more other things specific to the reliability of your services.
I'm not sure this sentence adds a lot of value.  Instead I would include a link to the [Nginx reverse proxy documentation](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).

Something like
"The following example demonstrates using both Nginx and Express for serving an SSR Quasar web app.  It is recommend to review the [Nginx documentation](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to better understand the different parameters before using in a production scenario."

2020-10-14 18:03 UTC, hawkeye64 commented on docs/src/pages/quasar-cli/developing-ssr/deploying.md
> +This line tells to Nginx to look for the file requested and if it can't be found pass the request to the location `@backend` that proxyes requests to our Express web server served by Node.js.
Should be "proxies", not "proxyes"

2026-08-18 08:47 UTC, rstoenescu commented
Thanks for this, and sorry it sat for so long.

We're clearing out the PR backlog. Every file this PR touches has since been moved or removed on `dev`, so the patch can no longer be rebased, and we're closing it rather than leaving it open indefinitely.

If the underlying need is still there, please open a fresh PR against current `dev` and we'll look at it promptly.

2026-08-18 08:47 UTC, closed without merging