Fix the mask  when reverse-fill - bug #8698
quasarframework/quasar pull request #8699
Opened 2021-03-28 00:13 UTC by livioalves

Fix the bug #8698, don't add a literal string to value when the value length is less then mask length.

**What kind of change does this PR introduce?** (check at least one)

- [ X ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ X ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ X ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ X ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ X ] It's been tested on a Cordova (iOS, Android) app
- [ X ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2021-03-29 15:04 UTC, pdanpdan requested changes

2021-03-29 15:04 UTC, pdanpdan commented on ui/src/mixins/mask.js
> +        if (typeof maskDef === 'string' && valIndex >= 0) {
I tested and you can move that condition inside the for.

2021-03-29 15:04 UTC, pdanpdan commented
Good catch.

2026-08-18 08:47 UTC, rstoenescu commented
Thanks for this, and sorry it sat for so long.

We're clearing out the PR backlog. Every file this PR touches has since been moved or removed on `dev`, so the patch can no longer be rebased, and we're closing it rather than leaving it open indefinitely.

If the underlying need is still there, please open a fresh PR against current `dev` and we'll look at it promptly.

2026-08-18 08:47 UTC, closed without merging